### ISSUE TITLE
Looking for example use cases and documentations

### ISSUE THREAD

**Issue by VladZawinski** [adidas/mvi#23]
Is there any fully explained documentation about this library? trying it out without knowledge of particular library is a red flag for me.

**Comment by jzeferino** [comment]
we are working on that, expect to have it ready in the near future. 
for now what we have to help with that is the https://github.com/adidas/mvi/blob/main/docs/README.md.

hold tight, more updates coming soon.

**Comment by enzoftware** [comment]
Hello, any updates on the documentation improvement for this? I want to help if needed.

**Comment by kazimad** [comment]
any updates?

**Comment by extmkv** [comment]
@jzeferino is currently working on it, and should be available in a few weeks.

**Comment by kazimad** [comment]
Hi there, is there any update here ? 🙄

**Comment by jzeferino** [comment]
i'm working on a sample app showcasing the usage of it before having the proper docs so you can take a look.

**Comment by jzeferino** [comment]
were added a sample here: https://github.com/adidas/mvi/tree/main/mvi-sample

you can take a look.

later tests and more formal documentation will be added later.

**Comment by kazimad** [comment]
thank you
